env:
  global:
    - SWIFT_VERSION=4.0

install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

jobs:
  include:
    - stage: test
      os: linux
      language: generic
      dist: trusty
      sudo: required
      script: swift build
    - stage: test
      os: osx
      osx_image: xcode9
      script: swift test
    - stage: test
      os: osx
      osx_image: xcode9
      script:
      - swift package generate-xcodeproj
      - xcodebuild -project JWT.xcodeproj -scheme JWT-Package build -sdk macosx
    - stage: test
      os: osx
      osx_image: xcode9
      script:
      - swift package generate-xcodeproj
      - xcodebuild -project JWT.xcodeproj -scheme JWT-Package build -sdk iphonesimulator
    - stage: test
      os: osx
      osx_image: xcode9
      script: swift package generate-xcodeproj
      - xcodebuild -project JWT.xcodeproj -scheme JWT-Package build -sdk appletvsimulator
    - stage: test
      os: osx
      osx_image: xcode9
      script:
      - swift package generate-xcodeproj
      - xcodebuild -project JWT.xcodeproj -scheme JWT-Package test -sdk watchsimulator
